"""Tests for the RetinaFace-R34 port + Detectorv1 integration.

Pins three layers of contract:

1. **Model**: ``RetinaFace`` constructs cleanly and produces the right
   tensor shapes for a batched input.
2. **Wrapper**: ``Retinaface`` (the ``__call__`` interface used by Detectorv1
   and pretrained.py) does its postprocess on-device, accepts batches,
   and produces equivalent per-image output for both batched and serial
   calls.
3. **Detectorv1 integration**: ``Detectorv1(face_model='retinaface')``
   builds, detects faces in a real test image, and propagates NaN-filled
   pose columns (since R34 has no head-pose regression).

Most tests skip if the local-fixture safetensors file is missing; the
file is generated by ``scripts/prepare_retinaface_r34.py``. CI should
populate it from the HF download once the file is uploaded.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest
import torch

from feat.face_detectors.Retinaface.Retinaface_model import RetinaFace, RETINAFACE_R34_CFG
from feat.face_detectors.Retinaface.Retinaface_test import Retinaface
from feat.utils.io import get_test_data_path


# Local safetensors file produced by scripts/prepare_retinaface_r34.py.
# The PR description includes an upload step; once the file is on HF the
# Retinaface wrapper will fetch it automatically. For local dev, point at
# the temp file or skip.
_LOCAL_WEIGHTS = Path("/tmp/py-feat-v2-models/retinaface_r34.safetensors")


def _have_weights() -> bool:
    return _LOCAL_WEIGHTS.exists()


def _load_local_weights(model: RetinaFace) -> RetinaFace:
    from safetensors.torch import load_file

    state_dict = load_file(str(_LOCAL_WEIGHTS))
    model.load_state_dict(state_dict, strict=True)
    return model


def _make_wrapper(device="cpu"):
    """Build the Retinaface wrapper without HF download, weights loaded locally."""
    rf = Retinaface(device=device, pretrained=None)
    _load_local_weights(rf.net)
    rf.net.to(rf.device).eval()
    return rf


# -------------------- model-level (no weights needed) --------------------


def test_retinaface_model_constructs_with_default_cfg():
    """Builds without errors; backbone is torchvision resnet34."""
    model = RetinaFace()
    assert model.cfg["name"] == "resnet34"


def test_retinaface_model_forward_shapes():
    """Forward on a dummy [1, 3, 320, 320] input returns the right shapes."""
    model = RetinaFace().eval()
    x = torch.zeros(1, 3, 320, 320)
    with torch.no_grad():
        bbox, conf, ldm = model(x)
    # 320x320 with strides 8/16/32 + 2 anchors per location:
    # 40x40*2 + 20x20*2 + 10x10*2 = 4200
    assert bbox.shape == (1, 4200, 4)
    assert conf.shape == (1, 4200, 2)
    assert ldm.shape == (1, 4200, 10)


def test_retinaface_model_rejects_non_resnet34_cfg():
    """Only the ResNet34 backbone is shipped here. Other configs error
    explicitly so a user passing a stale legacy cfg fails loudly."""
    bad_cfg = dict(RETINAFACE_R34_CFG)
    bad_cfg["name"] = "mobilenet0.25"
    with pytest.raises(ValueError, match="resnet34"):
        RetinaFace(bad_cfg)


# -------------------- Detectorv1 / MPDetector face_model validation -------


def test_detector_supports_retinaface():
    """`face_model='retinaface'` must be a recognized value on `Detectorv1`,
    same as on `MPDetector`. The shorter name is the canonical kwarg
    across both classes; the underlying HF repo retains the
    backbone-tagged `py-feat/retinaface_r34` filename."""
    from feat.detector import Detectorv1

    assert "retinaface" in Detectorv1._SUPPORTED_FACE_MODELS
    assert "img2pose" in Detectorv1._SUPPORTED_FACE_MODELS
    # Sanity: the tagged-backbone alias from earlier v0.7-dev iterations
    # is no longer accepted - users must move to the unified spelling.
    assert "retinaface_r34" not in Detectorv1._SUPPORTED_FACE_MODELS


def test_detector_rejects_unknown_face_model():
    """Validation must surface a clear error before any weight download."""
    from feat.detector import Detectorv1

    with pytest.raises(ValueError, match="face_model must be one of"):
        Detectorv1(face_model="not_a_real_model")


def test_detector_rejects_legacy_retinaface_r34_kwarg():
    """The `'retinaface_r34'` alias was dropped in v0.7.0 in favor of
    the shorter `'retinaface'`. Users on `v0.7-dev` who were already
    passing the old name must update."""
    from feat.detector import Detectorv1

    with pytest.raises(ValueError, match="face_model must be one of"):
        Detectorv1(face_model="retinaface_r34")


# -------------------- wrapper-level (needs weights) ----------------------


@pytest.mark.skipif(not _have_weights(), reason="local R34 safetensors not present")
def test_wrapper_detects_single_face():
    """Single face detected with high confidence at expected bbox location.

    The bbox-center bracket guards against channel-order regressions: the
    model was trained on BGR (cv2.imread) but py-feat tensors are RGB
    (PILToTensor). The wrapper applies mean-subtraction in RGB order
    (123, 117, 104). Flipping those constants to BGR (104, 117, 123) will
    still produce a face detection because BatchNorm absorbs some bias,
    but bbox center and score will drift noticeably. The bracket below is
    tight enough to catch that class of bug."""
    rf = _make_wrapper()
    path = os.path.join(get_test_data_path(), "single_face.jpg")
    if not os.path.exists(path):
        pytest.skip("single_face.jpg test image missing")
    from torchvision.io import read_image

    img = read_image(path).float().unsqueeze(0)  # [1, 3, H, W]
    out = rf(img)
    assert len(out) == 1
    assert len(out[0]) == 1, f"expected 1 face, got {len(out[0])}"
    x1, y1, x2, y2, score = out[0][0]
    # With correctly-calibrated RGB-order mean, score is ~1.0 on this image.
    assert score > 0.95, f"score {score:.4f} below 0.95 - check channel order"
    assert x2 > x1 and y2 > y1
    # Empirical face center on single_face.jpg with RGB-order mean: (280, 269).
    # 25-pixel bracket catches the channel-order class of bug, which shifts
    # the bbox by ~10-50 pixels in our manual A/B testing.
    cx, cy = (x1 + x2) / 2, (y1 + y2) / 2
    assert 255 < cx < 305, f"face center x={cx:.0f} out of (255, 305)"
    assert 244 < cy < 294, f"face center y={cy:.0f} out of (244, 294)"


@pytest.mark.skipif(not _have_weights(), reason="local R34 safetensors not present")
def test_wrapper_detects_multiple_faces():
    rf = _make_wrapper()
    path = os.path.join(get_test_data_path(), "multi_face.jpg")
    if not os.path.exists(path):
        pytest.skip("multi_face.jpg test image missing")
    from torchvision.io import read_image

    img = read_image(path).float().unsqueeze(0)
    out = rf(img)
    assert len(out) == 1
    # Test image has 5 faces; a strong detector at default thresholds gets all of them.
    assert len(out[0]) >= 4, f"expected >=4 faces, got {len(out[0])}"


@pytest.mark.skipif(not _have_weights(), reason="local R34 safetensors not present")
def test_wrapper_batched_matches_serial():
    """Batched call produces per-image outputs equivalent to serial 1-image
    calls. Keeps us honest about the on-device batched-NMS contract."""
    rf = _make_wrapper()
    paths = [
        os.path.join(get_test_data_path(), "single_face.jpg"),
        os.path.join(get_test_data_path(), "multi_face.jpg"),
    ]
    for p in paths:
        if not os.path.exists(p):
            pytest.skip(f"{p} missing")

    from feat.data import ImageDataset
    from torch.utils.data import DataLoader

    ds = ImageDataset(paths, output_size=640, preserve_aspect_ratio=True, padding=True)
    loader = DataLoader(ds, batch_size=2)
    batch = next(iter(loader))["Image"]

    batched_out = rf(batch)
    serial_out = [rf(batch[i : i + 1])[0] for i in range(batch.shape[0])]

    assert len(batched_out) == len(serial_out) == 2
    for img_idx in range(2):
        assert len(batched_out[img_idx]) == len(serial_out[img_idx]), (
            f"image {img_idx}: batched got {len(batched_out[img_idx])} "
            f"faces, serial got {len(serial_out[img_idx])}"
        )


# -------------------- Detectorv1 integration -------------------------------


@pytest.mark.skipif(not _have_weights(), reason="local R34 safetensors not present")
def test_detector_with_retinaface_detects_multi_face():
    """End-to-end: Detectorv1(face_model='retinaface') -> detect() -> Fex.
    Verifies the dispatch in detect_faces, the per-frame extraction path,
    and that pose columns end up NaN."""
    # Stub the HF download to point at the local safetensors so the test
    # doesn't require the file to be uploaded yet. The Retinaface wrapper
    # does a local import inside __init__, so we have to patch the source
    # symbol on feat.utils, not the importing module.
    import feat.utils as _utils

    orig_dl = _utils.hf_hub_download_with_fallback

    def _local_download(repo_id, filename, fallback_filename, cache_dir):
        if "retinaface_r34" in repo_id:
            return str(_LOCAL_WEIGHTS)
        return orig_dl(repo_id, filename, fallback_filename, cache_dir)

    _utils.hf_hub_download_with_fallback = _local_download
    try:
        from feat.detector import Detectorv1

        det = Detectorv1(face_model="retinaface", device="cpu", au_model="svm")
        assert det.info["face_model"] == "retinaface"
        # facepose_model = 'pose_mlp' indicates pose came from the Pose-MLP
        # (distilled from img2pose) rather than img2pose's native regression.
        # The legacy DLT-PnP backend was removed; retinaface always uses the MLP.
        assert det.info["facepose_model"] == "pose_mlp"

        path = os.path.join(get_test_data_path(), "multi_face.jpg")
        if not os.path.exists(path):
            pytest.skip("multi_face.jpg missing")

        fex = det.detect(path)
        assert len(fex) >= 4, f"expected >=4 faces, got {len(fex)}"
        # Pose columns are populated via the Pose-MLP. Each angle must be a
        # finite number in radians (between -pi and +pi).
        import math
        for col in ("Pitch", "Roll", "Yaw"):
            vals = fex[col]
            assert not vals.isna().any(), f"{col} has NaN values"
            assert (vals.abs() <= math.pi).all(), f"{col} out of [-pi, pi]"
        # Sanity bound: faces in multi_face.jpg are all roughly frontal
        # (pictured group facing the camera), so mean Yaw magnitude across
        # the 5 detected faces should be modest. Loose enough to pass on
        # any reasonable PnP solution; tight enough to catch a regression
        # where the solver returns near-pi values for every face.
        assert fex.Yaw.abs().mean() < math.radians(45), (
            f"mean |Yaw| = {math.degrees(fex.Yaw.abs().mean()):.1f} deg "
            "on a roughly-frontal multi-face group is suspicious"
        )
        # Face / emotion outputs are real numbers.
        assert not fex.FaceRectX.isna().any()
        assert (fex.happiness > 0).any()
    finally:
        _utils.hf_hub_download_with_fallback = orig_dl
